#!/bin/bash
#shellcheck disable=2164,2046,1090

# 获取当前脚本所在目录
BASE_DIR=$(cd `dirname $0`; pwd)
source ${BASE_DIR}/global.sh

function _install_my_tools(){
	create-dirs

	install-platform-package
	install-go-packages
	install-python-packages
	install-node-packages

	create-links

	# start new era...
	echo "Installation done!"
	echo "Restart your Terminal Or source ~/.zshrc"
}

_install_my_tools
