- name: lftp
  type: docker-image
  source:
    repository: machinerytool/concourse-lftp-resource
    tag: latest
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: v0.3.0
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
- name: artifactory
  type: docker-image
  source:
    repository: pivotaldata/concourse-artifactory-resource
- name: github-release
  type: docker-image
  source:
    repository: concourse/github-release-resource