#!/usr/bin/env python
# _*_ coding: utf-8 _*_

import os
import shutil

import sqlite3

sql_file = os.environ.get("ANNOTATION_FILE", "/Users/baotingfang/abc.sqlite")


def update_location():
    work_dir = os.path.dirname(sql_file)
    db_file_name = os.path.basename(sql_file)
    new_db_file = os.path.join(work_dir, "new_%s" % db_file_name)
    shutil.copy(sql_file, new_db_file)

    conn = sqlite3.connect(new_db_file)

    conn.execute('update annotations set entity=replace(entity, "gpdb-reading", "gpdb-gp2gp")')
    conn.commit()
    conn.close()

if __name__ == '__main__':
    update_location()
