#!/usr/bin/env python
# _*_ coding: utf-8 _*_
import sys

from lib.gpdb.logs import get_the_latest_master_log_file, output_csv, get_the_latest_segment_log_file

if __name__ == '__main__':

    seg_id = 0
    try:
        seg_id = int(sys.argv[1])
    except:
        pass

    level = "ALL"
    if len(sys.argv) > 2:
        # 设置关注的日志级别: ERROR, LOG, ....
        level = sys.argv[2].upper()

    seg_log = get_the_latest_segment_log_file(seg_id=seg_id)
    output_csv(seg_log, show_level=level)
