#!/usr/bin/env bash
#shellcheck disable=1090

# set -euxo pipefail
set -euo pipefail

source ${BASE_DIR}/starter/functions.sh
source ${BASE_DIR}/init/profile.d/gpdb.sh
source ${BASE_DIR}/init/profile.d/postgres.sh

gpdb-env-set "$@"
GPDB_SRC=`pwd` _gpdb-compile "$@"