#!/usr/bin/env bash

# set -euxo pipefail
set -euo pipefail

source ${BASE_DIR}/init/profile.d/git.sh
source ${BASE_DIR}/init/profile.d/gpdb.sh
source ${BASE_DIR}/init/profile.d/postgres.sh

GPDB_SRC=`pwd` _gpdb-clean "$@"
