#!/usr/bin/env bash
#shellcheck disable=1090

set -eu
set -o pipefail

source ${BASE_DIR}/starter/functions.sh
source ${BASE_DIR}/init/profile.d/postgres.sh
source ${BASE_DIR}/init/profile.d/git.sh
source ${BASE_DIR}/init/profile.d/gpdb.sh

GPDB_SRC=`pwd` _gpdb-full-compile "$@"
