#!/usr/bin/env bash
# set -euxo pipefail
# 由于source greenplum_path的问题， 这里不能使用set -u
set -eu
set -o pipefail

source ${BASE_DIR}/init/alias.sh
source ${BASE_DIR}/init/profile.d/gpdb.sh
source ${BASE_DIR}/init/profile.d/postgres.sh

_gpdb-reinit "$@"